### PR TITLE
Get rid of Podman, Grafana, InfluxDB

### PR DESCRIPTION
**Pull request by cjeanneret**
This new code change, while huge, makes things easier to manage. It
reduces the footprint, dropping dependencies, especially for the graph
part.

It now uses plain fyne canvas in order to show current, average and max
values for split time, power and strokes per minutes.

From now on, the history consists in CSV files. This allows to load them
in any sheet software (Excel, LibreCalc, even GoogleSheet) and get nice
graphs out of the data.

Please note there's an additional field, "Timestamp", holding the time
of the stroke - it's different than the TotalTime, since this one shows
the exercise duration.

### CODE REVIEW

**Comment by timcolson** [comment]
I look forward to checking this out! Replying to email notification partly to see where it goes, and to not a tiny spelling error:
s/exercice/exercise/
-Tim

**Comment by cjeanneret** [comment]
Hey @timcolson  :). It should work just fine - I'll do a session tomorrow with this new code, and see how it goes.
For the spelling..... dang - but it's in the first commit of the lot, and... I'll be lazy regarding the whole rebase...

**Comment by timcolson** [comment]
LOL - Just realized my email reply had a spelling error in "not". I see it was just added to the pull request "conversation". Also noted that **markdown** works on the web comments (doing that now), but not sent in via email. 🧙 

I see the first two commits have red X's... says build failed... real problem?
```
pkg/containerUtils/apolloUtils.go:76:18: cfg.PodName undefined (type *apolloUtils.ApolloConfig has no field or method PodName)
649
pkg/containerUtils/apolloUtils.go:79:63: cfg.PodSocket undefined (type *apolloUtils.ApolloConfig has no field or method PodSocket)
650
Error: Process completed with exit code 2.
```

**Comment by cjeanneret** [comment]
@timcolson so the errors were legit, but the 3rd patch corrected them. I still need to do some cosmetics on the new UI, but it's WORKING! Could register a whole 25 minutes session today. Just really need to make things bigger, and maybe chose better colors. It's fast and light, guess the pi4 will be able to run it without any issue :).

**Comment by cjeanneret** [comment]
will do a new session tomorrow with this code in order to ensure it's OK for, at least, my 25-30 minutes, and if everything's fine, I'll merge it on master and cut a new tag.

**Comment by timcolson** [comment]
Excellent work! I just checked out the branch. NewB build problems with Go. Steps would help me. :) 

Lots of this error:
 missing go.sum entry for module providing package github.com/avast/retry-go; to add:
	go mod download github.com/avast/retry-go

Running Go 1.16 - which [Go Blog Feb 2021](https://blog.golang.org/go116-module-changes <https://blog.golang.org/go116-module-changes>) says module building has changed in 1.16. I saw 1.14 in go.mod …feel like I’m missing a step to install the dependencies, which I expected “go build” to do.

**Pull request merged**
